CREATE TABLE Posts (
    PostID INT PRIMARY KEY AUTO_INCREMENT,
    CreatorID INT,
    Likes INT DEFAULT 0,
    Caption VARCHAR(255),
    Tags TEXT,
    ImageURL VARCHAR(255),
    ImageID VARCHAR(255),
    Location VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CreatorID) REFERENCES Users(UserID)
);